version: '3'

services:
  database:
    image: 'postgres:15-alpine'
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pg
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data: