version: '3.5'

services:
    pgadmin:
        image: dpage/pgadmin4
        environment: 
            PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - 5050:80
        restart: always
        volumes: 
            - pgadmin:/root/.pgadmin

volumes:
    pgadmin: